global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'application'
    static_configs:
      - targets: ['app:8081']  # Using Docker service name
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'simulator'
    static_configs:
      - targets: ['simulator:8082']  # Using Docker service name
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
